### ISSUE TITLE
Implement reusable composite actions to release server app

### ISSUE THREAD

**Issue by nhan-nguyen-se** [Atlas-Authority/atlassian-marketplace-release-action#1]
Copy the actions in MMCC and parameterized them so that they can be used across server repositories. Basically there should be two actions:
- build jar and upload the result to GitHub release assets
- release the app to Atlassian server marketplace

The above actions must not reference any secret directly. Instead passing the secrets as action input.

**Comment by bberenberg** [comment]
I have made this repo public.
