### ISSUE TITLE
Detect addon-key base on atlassian-plugin.ml

### ISSUE THREAD

**Issue by nhan-nguyen-se** [Atlas-Authority/atlassian-marketplace-release-action#3]
Currently `build-jar` action detects addon-key using pattern `project.groupId`.`project.artifactId`. However that pattern does not work with tableau for confluence plugin. Addon key of tableau for confluence is just `tableau-plugin`.

As per discussion with @khanguyen88 the best solution should be extracting the addon-key from `atlassian-plugin.xml`:
```xml
<atlassian-plugin key="tableau-plugin">...</atlassian-plugin>
```

To do that the action needs to do some xml parsing. There are a couple of actions out there for that purpose but they are not fit with our need. They are able to read the tag value only, not the attribute value as what we need. I created an [PR](https://github.com/mavrosxristoforos/get-xml-info/pull/7) to the upstream for an enhancement to support our need.

The other option is parameterize the addon-key information so that it can be provided by the repositories which use this release action. But it's less automatic.

cc: @bberenberg

**Comment by bberenberg** [comment]
Maybe have a default approach that can be overridden on a per repo basis? Is there something like env variables for actions?

**Comment by bberenberg** [comment]
Yeah let's keep it simple. Also let's make sure we put together a readme for how to use this action.

**Comment by nhan-nguyen-se** [comment]
The PR to the upstream get merged sooner than I think, and the change from our side is pretty simple so I decide to use the xml parsing approach. I also put the readme to this repo.
